version: '3.4'

services:
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - /data/mongodb:/data/mongodb
  
  sqlserver:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2017-latest
    volumes:
      - /data/sqldb:/data/sqldb

  cache:
    image: redis:alpine
    container_name: redis
    volumes:
      - /data/redis:/data
  
    
  um.users.service:
    image: um.users.service
    container_name: um.users.service
    build:
      context: .
      dockerfile: UsersManagement/TrialsSystem.UsersService/Dockerfile
    depends_on:
      - mongo